### ISSUE TITLE
non_model_error_no_signature_of _method

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#11]
Hi, I am trying to run LncPipe for "Rat" data and had provided coding and ncRNas gtf files and CPAT logit model as described in the other issue. 

I am getting the following error:
```
ERROR ~ No signature of method: sun.nio.fs.UnixPath.into() is applicable for argument types: (_nf_script_9e483c9b$_run_closure14) values: [_nf_script_9e483c9b$_run_closure14@76a36b71]
Possible solutions: init(), find(), any(), list(), min(), any(groovy.lang.Closure)

 -- Check script 'LncRNAanalysisPipe.nf' at line: 275 or see '.nextflow.log' file for more details
```

Line 275 of my LncRNAnalysisPipe.nf is:
```
    Known_coding_gtf.into{proteinCodingGTF; proteinCodingGTF_forClass}
```

[issue#10_nextflow.log](https://github.com/likelet/LncPipe/files/2298474/issue.10_nextflow.log)

**Comment by likelet** [comment]
thanks for reporting this bug, we did not test too much on non-human data, i will check this soon .

**Comment by sateeshperi** [comment]
I was able to get it to work by making the following changes; I deleted the line 275 and then modified line 1095 as follows:
```
file gencode_protein_coding_gtf from Known_coding_gtf
```
and it worked. Also I was having issues with the 'merged.gtf' file having 'chr' prefix which was not compatible with PLEK and CPAT so, I added the following to fix that at line 716 after stringtie merge:
```
 sed -i 's/chr//g' merged.gtf
```

**Comment by likelet** [comment]
I am not sure wether your modifications worked for all cases, you can fork and make a branch for your changes. In some cases, e.g. reference from ensemble databases, the annotation file  has no `chr` prefix in there chromosome id, that's why we suggested people using the concordant reference and annotation file in their analysis. Considering this,  I would rather not provide the adjust functions in the script which in turns throws out errors instead of producing wrong result.
