### ISSUE TITLE
lncRNA_Filtering_Criteria

### ISSUE THREAD

**Issue by sateeshperi** [likelet/LncPipe#12]
As stated in your paper, these following are the initial filtering criteria for lncRNAs:
* length > 200
* Exon number > 2

In these, what is the significance and rationale for 'Exon count > 2' and is it applicable to all species?

**Comment by likelet** [comment]
In our pipe, we retained the lncRNA that has 2 or more exons as candidates(I think there are missing a `=` in the print version, also for `length`). This  is because we think that single-exon sourced lncRNAs  are more likely from unreliable assembly of RNA-seq data and only focus on multiexonic transcripts.   
also, i think this criteria is also suitable for other species according to this [paper ](http://genesdev.cshlp.org/content/25/18/1915.full.html)  
http://genesdev.cshlp.org/content/25/18/1915.full.html
