### ISSUE TITLE
Nextflow per-process resources

### ISSUE THREAD

**Issue by drejom** [likelet/LncPipe#25]
Hi, thanks so much for making your pipeline available -  it looks very useful!! 
I wonder if you can clarify if you intended it to be run on a single machine with nextflow's 'local' executor, and not on a cluster? Looks like you've written some logic to assign the number of threads etc for some processes, but it seems this is determined ad hoc by whats available on the machine running the pipeline, rather than declaring it explicitly. 
Nextflow is most useful when the resources are specified on a per-process basis, then the script can be run on any infrastructure, from a desktop to a cluster. Before i go hacking, I wonder if theres a reason you've avoided going this route?

**Comment by likelet** [comment]
Thanks for being interested in our pipeline. This is a great question that i was asked before. 
Actually, this pipeline has been tested on both local server and cluster (both under pbs and slurm system) so far.  At the very start of the project, i tried making the pipe can automatically determine the available resource, but i found it was hard to cope with tradeoff between cpu and mem in all parallel processes( due to my limited  experience on this before). Thus, i discarded the strategy that dynamic resource all processes, while required users manually set the `maxForks ` parameter in config file to adjust the some of the processes  instead.
We have also assessed the IO and running efficiency of each process in our local machine and set the mem or cpus minimizing of the running time of the test data (according to the sample number and size). This is a compromised strategy the is not elegant as Nextflow expected. 
I will keep on optimizing this as hard as i can.  And also welcome people to join us or give advices .
Hope the above info can address your concerns.
Qi Zhao

**Comment by drejom** [comment]
OK, cool...I've hacked a few changes to allow per-process resource requests in an additional config file. I can try a pull request or fork, if you're interested? I've taken inspiration from the pipelines at [https://nf-co.re/](https://nf-co.re/). Would you consider porting this pipeline to that setup? I'd be happy to help if you think it looks worthwhile?

**Comment by likelet** [comment]
Sure, i'd like to do that. 
Of course, you can fork or try a new PR on additional config file. i opened a test data repo [here](https://github.com/likelet/LncPipeTestData) for people like you to have a quick test of the pipeline once  your docker env was well-configured (which need less than 10 mins in a single run). 
I know about the nf-cores that have workflows in a high quality, i think it take some time to port this pipeline to it, but it's worth a try. 
thanks

**Comment by brunohhomem** [comment]
Hi,
I've been trying use your pipeline for almost two months. First, I tried to run on my notebook (Acer Aspire. i3, 6GB ram), just to try understand how it works. This week, I managed to make it work on server of my lab (Dell Power Edge T430, with Xeon 2303 and 10 gb of memory) with your LNCTestData (in 30 minutes). 
I want to know, if you can tell me how much hardware I need to run perfectly the pipe, my professor wants to try it on amazon cloud, but I don't know how much we need or if I can just upgrade my server.
Thanks for your help.

**Comment by likelet** [comment]
hi @brunohhomem 
the testdata was trimed in a small amount for test only (only chrX data was provided). I do not know how much sample you have and how big your data file is.  In my side , i have a server with 128G mem and 50 cores  to run about 6 samples (3 normal vs 3 tumor, 12 file in total, each sample have 20-30M reads), it take 2 and a half hours.  as I know, the default running not comsume too much resouces, you can set 'para' =6 and 'qc' =6 in config file and run. if the mapping and the kallisto run failed, plz reduce the `para` value accordlingly. 
hope those info can help you select servers.

**Comment by brunohhomem** [comment]
We don't have samples neither data. My professor wants to start to analysing the LNC. So I've been studying how your pipe works and trying to make work in our server. I'll try what have you suggested, thank for everything.

**Comment by brunohhomem** [comment]
There are any param where I can set memory? Like "para" and "qc" that you've suggested. I don't care if take much time to do the process, since we are just trying to learn and understand the pipe.

**Comment by likelet** [comment]
Currently, no mem limited was declared in the pipe, a simple calculation is to find the largest mem use process by setting para and qc into 1 (or provide only one sample) and run pipe with `-with-timeline timeline.html`.  In the `timeline.html`, you can easily get the the mem usage of each process. 
According to the usage, you  might be able to determine how much mem and cpu need in your best case. 
like this 
https://github.com/likelet/LncPipeTestData#run-information

**Comment by brunohhomem** [comment]
Okay, thanks :D
